#!/usr/bin/env bash
# World wide web.

subdomains=( "www" "lb-01" "web-01" "web-02" )

if [ $# -eq 2 ]; then
   dig "$2.$1" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER' | awk -v subd="$2" '{print "The subdomain "subd" is a "$4" record and points to "$5}'
else
	for i in "${subdomains[@]}"; do
	    	  dig "$i.$1" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER' | awk -v subd="$i" '{print "The subdomain "subd" is a "$4" record and points to "$5}'
 	done
fi
