#!/usr/bin/env bash
# Server config web-01 and web-02

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://twitter.com/artesanaljanne/status/1393725121077129216 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/h404.html
sed -i '/listen 80 default_server/a error_page 404 /h404.html;\nlocation = /h404.html {\n\troot /var/www/html;\n\tinternal;\n}' /etc/nginx/sites-available/default
sed -i "/listen 80 default_server/a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
