#!/usr/bin/env bash
# Server config. 

# install nginx
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo service nginx start

# Default and error pages
echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html

# Run default and error pages
match="server_name _;"
new="\n\tlocation /redirect_me {\n\t\treturn 301 http://janne-artesanal.tech;\n\t}"
sed -i "/$match/a\\$new" /etc/nginx/sites-available/default

match="server_name _;"
new="\n\terror_page 404 /error404.html;\n"
sed -i "/$match/a\\$new" /etc/nginx/sites-available/default

# Header that sends the hostname
match="then fall back to displaying a 404"
new="\n\t\tadd_header X-Served-By $HOSTNAME;\n"
sed -i "/$match/a\\$new" /etc/nginx/sites-available/default

# Restart the server
service nginx restart
